### ISSUE TITLE
Have Implementation Validated by ZATCA

### ISSUE THREAD

**Issue by obahareth** [mrsool/zatca#3]
We're currently in talks with ZATCA to validate this implementation. It's made to match the docs as close as we could understand.

**Comment by GeeSuth** [comment]
if accepted should I do one In .NET 
I think .NET it's more popular and used in more systems.

Thanks for sharing

**Comment by naeem5364** [comment]
is this approved by zatca?

**Comment by obahareth** [comment]
> is this approved by zatca?

@naeem5364 

It is not officially approved or looked at by ZATCA. However ZATCA has released an [official SDK](https://zatca.gov.sa/en/E-Invoicing/SystemsDevelopers/ComplianceEnablementToolbox/Pages/DownloadSDK.aspx), and this Rubygem's output is designed to match the SDK's. You can verify this yourself if you wish, and report any errors here, or make a pull request to fix them.

I personally am in the process of having someone from ZATCA take a look at this gem, but for the meantime the output matches their official SDK.

**Comment by obahareth** [comment]
> if accepted should I do one In .NET I think .NET it's more popular and used in more systems.
> 
> Thanks for sharing

@GeeSuth Thank you for the kind words.

Definitely more packages in more languages would help out developers to implement this. We use Ruby and thought to open source our implementation in the hopes that it helps others, many other languages still need an open source implementation for E-Invoicing.

**Comment by GeeSuth** [comment]
Yes.
You are right, 
I understand it. 
BTW I finish the Library in .Net
https://github.com/GeeSuth/GeeSuthSoft.KSA.ZATCA


Regards

**Comment by alan-sapaad** [comment]
@obahareth what if the value contains Arabic characters (in seller name), that is outside ASCII set ?

**Comment by obahareth** [comment]
@alan-sapaad It works out, there was a bug in it that was fixed in the latest release. There's also unit tests for unicode variants.

**Comment by alan-sapaad** [comment]
Nice, I just saw the test cases.
I had also implemented a solution, exactly like this source code. But when I validated it with the SDK, it was not showing arabic in the decoded tags. I just tried with a base64 encoded value from the test case as well.

I think it has to do with the way the SDK is rendering characters ?

**Comment by GeeSuth** [comment]
@alan-sapaad I face same problem with our tools. https://github.com/GeeSuth/GeeSuthSoft.KSA.ZATCA/issues/1
I was can reflect to Arabic Two<>way , but in ZATCA SDK can't.. 
I Think the problem was from Console 
try to write code convert from BASE64 To DATA. with Arabic Content
